### PR TITLE
fixed: blank tabs for example links

### LINKED ISSUE #23: click "examples" should just change URL instead of opening a new tab
current behavior:
- visit https://run.thala.dev/
- click "0x1"
- open a new tab https://run.thala.dev/?account=0x1&network=mainnet

expected behavior:
- visit https://run.thala.dev/
- click "0x1"
- change the current tab URL to https://run.thala.dev/?account=0x1&network=mainnet

### PR DESCRIPTION
**Pull request by mastercodercat**
fixed #23

### CODE REVIEW

**Comment by 0xbe1** [comment]
@mastercodercat Try clicking 0x3 - it doesn't really work

**Comment by 0xbe1** [comment]
@mastercodercat 
Can we solve this without adding the logic to AccountInput?
Can we basically click 0x3, which is equivalent to typing the new URL in the current tab, then pressing refresh?
can we do so by leveraging the button onclick? (just a guess)

File: components/AccountInput.tsx [hunk 1]
```diff
@@ -1,15 +1,19 @@
 import { Input } from "@chakra-ui/react";
+import { useRouter } from "next/router";
 import { useController, useFormContext } from "react-hook-form";
 import { TxFormType } from "../lib/schema";
 
 export default function AccountInput() {
   const { control, resetField } = useFormContext<TxFormType>();
+  const router = useRouter();
```
Comment (0xbe1) [inline components/AccountInput.tsx:8]: rm

File: components/AccountInput.tsx [hunk 2]
```diff
@@ -1,15 +1,19 @@
 import { Input } from "@chakra-ui/react";
+import { useRouter } from "next/router";
```
Comment (0xbe1) [inline components/AccountInput.tsx:2]: rm

**Review by 0xbe1 — APPROVED** [review]
lgtm
